# Generated by Django 4.0 on 2021-12-12 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FrontPageCarousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_image', models.ImageField(upload_to='site_images')),
                ('discount', models.IntegerField()),
                ('offer_title', models.CharField(max_length=200)),
            ],
        ),
    ]
