# Generated by Django 4.0 on 2021-12-12 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontpagecarousel',
            name='offer_product',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
