# Generated by Django 4.0 on 2021-12-13 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_shop', '0003_newproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unisex')], max_length=1)),
                ('img', models.ImageField(upload_to='site_images')),
                ('has_discount', models.BooleanField(default=False)),
                ('discount', models.IntegerField()),
                ('original_price', models.IntegerField()),
                ('discount_price', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='frontpagecarousel',
            name='offer_product',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='frontpagecarousel',
            name='offer_title',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='newproduct',
            name='product_type',
            field=models.CharField(max_length=20),
        ),
    ]
