# Generated by Django 4.0 on 2021-12-13 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_shop', '0006_alter_featuredproduct_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredproduct',
            name='discount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='featuredproduct',
            name='discount_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
