# Generated by Django 4.0 on 2021-12-13 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_shop', '0007_alter_featuredproduct_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredproduct',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Unisex', 'Unisex')], max_length=10),
        ),
    ]
