# Generated by Django 4.0 on 2021-12-13 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_shop', '0013_bestsellerproduct_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='site_images')),
                ('start_price', models.IntegerField()),
                ('cartegory', models.CharField(max_length=20)),
            ],
        ),
    ]
