# Generated by Django 4.0 on 2021-12-14 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_shop', '0017_rename_ourteams_ourteam'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=20)),
                ('published_date', models.DateTimeField(auto_now=True)),
                ('blog_title', models.CharField(max_length=100)),
                ('blog_image', models.ImageField(upload_to='site_images')),
            ],
        ),
    ]
