# Generated by Django 4.0 on 2021-12-14 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_shop', '0021_blogpost_blockpostdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='blog_desc',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='BlockPostDetails',
        ),
    ]
