# Generated by Django 4.0 on 2021-12-15 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_shop', '0022_blogpost_blog_desc_delete_blockpostdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Unisex', 'Unisex')], max_length=10)),
                ('img', models.ImageField(upload_to='site_images')),
                ('brand', models.CharField(max_length=50)),
                ('cartegory', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('sizes_available', models.CharField(choices=[('Small', 'X'), ('Medium', 'M'), ('Large', 'L'), ('Extra_Large', 'XL'), ('XX_large', 'XLL')], max_length=50)),
                ('has_discount', models.BooleanField(default=False)),
                ('discount', models.IntegerField(blank=True)),
                ('original_price', models.FloatField()),
                ('discount_price', models.FloatField(blank=True)),
            ],
        ),
    ]
