# Generated by Django 4.0 on 2021-12-15 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_shop', '0023_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='display_in',
            field=models.CharField(choices=[('Featured', 'Featured'), ('Best Seller', 'Best Seller'), ('Shop', 'Shop')], max_length=50, null=True),
        ),
    ]
