# Generated by Django 4.0 on 2021-12-16 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_shop', '0029_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BestSellerproduct',
        ),
        migrations.DeleteModel(
            name='FeaturedProduct',
        ),
    ]
