# Generated by Django 4.0 on 2021-12-16 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_shop', '0039_alter_item_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_image',
        ),
    ]
