# Generated by Django 4.0 on 2021-12-18 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_shop', '0042_alter_item_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Discount Price'),
        ),
        migrations.AlterField(
            model_name='item',
            name='original_price',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Price'),
        ),
    ]
