# Generated by Django 4.0 on 2021-12-18 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_shop', '0044_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='item',
            name='discount_price',
        ),
    ]
