# Generated by Django 4.0 on 2021-12-18 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_shop', '0046_item_discount_item_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_status',
            field=models.CharField(choices=[('In Stock', 'In Stock'), ('Not Available', 'Not Available'), ('Ready to Ship', 'Ready to Ship'), ('Sold Out', 'Sold Out'), ('Temporarily Out-of-Stock', 'Temporarily Out-of-Stock')], max_length=50, null=True, verbose_name='Item Status'),
        ),
    ]
