# Generated by Django 4.0 on 2022-01-02 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_shop', '0052_remove_cardproduct_cartegory_cardproduct_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewProduct',
            new_name='Offer',
        ),
    ]
