# Generated by Django 4.0 on 2022-01-24 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('new_shop', '0058_filter_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='price_filter_range',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='new_shop.filter_price'),
        ),
        migrations.AlterField(
            model_name='filter_price',
            name='price_range',
            field=models.CharField(choices=[('0 TO 249', '0 TO 250'), ('250 TO 349', '250 TO 349'), ('350 TO 499', '350 TO 449'), ('550 TO 599', '450 TO 549'), ('550 TO 999', '550 TO 999'), ('1000 TO 3999', '1000 TO 3999'), ('4000 TO 6000', '4000 TO 6000')], max_length=25),
        ),
    ]
