# Generated by Django 4.0 on 2022-02-03 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('new_shop', '0062_alter_blogpost_author_alter_blogpost_blog_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='new_shop.brand'),
        ),
    ]
