# Generated by Django 4.0 on 2022-02-03 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('new_shop', '0063_alter_item_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='new_shop.brand'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price_filter_range',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='new_shop.filter_price'),
        ),
    ]
