# Generated by Django 4.0 on 2022-02-18 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_shop', '0068_order_order_note'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-date',)},
        ),
        migrations.AddField(
            model_name='order',
            name='ref',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
