# Generated by Django 4.0 on 2022-05-31 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('new_shop', '0074_remove_item_brand_remove_item_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='quantity_available',
            field=models.IntegerField(default=7, verbose_name='Quantity in Stock'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='filter_price',
            name='price_range',
            field=models.CharField(choices=[('0 TO 10', '0 TO 10'), ('11 TO 20', '11 TO 20'), ('21 TO 50', '21 TO 50'), ('51 TO 100', '51 TO 100'), ('101 TO Above', '101 TO Above')], max_length=25),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='new_shop.category'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_status',
            field=models.CharField(choices=[('In Stock', 'In Stock'), ('Not Available', 'Not Available')], max_length=50, null=True, verbose_name='Item Status'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Price'),
        ),
    ]
