# Generated by Django 4.0 on 2021-12-13 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_shop', '0008_alter_featuredproduct_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='BestSellerproduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Unisex', 'Unisex')], max_length=10)),
                ('img', models.ImageField(upload_to='site_images')),
                ('has_discount', models.BooleanField(default=False)),
                ('discount', models.IntegerField(blank=True, null=True)),
                ('original_price', models.FloatField()),
                ('discount_price', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
