# Generated by Django 4.0 on 2021-12-13 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_shop', '0010_bestsellerproduct_sizes_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestsellerproduct',
            name='sizes_available',
            field=models.BooleanField(choices=[('Small', 'X'), ('Medium', 'M'), ('Large', 'L'), ('Extra_Large', 'XL'), ('XX_large', 'XLL')], default=False),
        ),
    ]
