# Generated by Django 4.0 on 2021-12-16 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_shop', '0027_remove_item_quantity_orderitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='brand',
            field=models.CharField(max_length=50, verbose_name='Item Brand'),
        ),
        migrations.AlterField(
            model_name='item',
            name='cartegory',
            field=models.CharField(max_length=50, verbose_name='Item Cartegory'),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(verbose_name='Item Description'),
        ),
        migrations.AlterField(
            model_name='item',
            name='discount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Discount'),
        ),
        migrations.AlterField(
            model_name='item',
            name='discount_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Discount Price'),
        ),
        migrations.AlterField(
            model_name='item',
            name='display_in',
            field=models.CharField(choices=[('Featured', 'Featured'), ('Best Seller', 'Best Seller'), ('Shop', 'Shop')], max_length=50, null=True, verbose_name='Diplayed In'),
        ),
        migrations.AlterField(
            model_name='item',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Unisex', 'Unisex')], max_length=10, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='item',
            name='has_discount',
            field=models.BooleanField(default=False, verbose_name='Has Discount'),
        ),
        migrations.AlterField(
            model_name='item',
            name='img',
            field=models.ImageField(upload_to='site_images', verbose_name='Item Image'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Item Name'),
        ),
        migrations.AlterField(
            model_name='item',
            name='original_price',
            field=models.FloatField(verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='item',
            name='sizes_available',
            field=models.CharField(choices=[('Small', 'X'), ('Medium', 'M'), ('Large', 'L'), ('Extra_Large', 'XL'), ('XX_large', 'XLL')], max_length=50, verbose_name='Size Avaailable'),
        ),
    ]
