# Generated by Django 4.0 on 2022-02-19 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_shop', '0071_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
