# Generated by Django 4.0 on 2021-12-12 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_shop', '0002_frontpagecarousel_offer_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='site_images')),
                ('discount', models.IntegerField()),
                ('product_type', models.CharField(max_length=200)),
            ],
        ),
    ]
