# Generated by Django 4.0 on 2021-12-13 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_shop', '0004_featuredproduct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredproduct',
            name='discount_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='featuredproduct',
            name='original_price',
            field=models.FloatField(),
        ),
    ]
