# Generated by Django 4.0 on 2021-12-14 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_shop', '0014_cardproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('feedback_content', models.TextField()),
                ('profile_pic', models.ImageField(upload_to='site_images')),
            ],
        ),
    ]
