# Generated by Django 4.0 on 2021-12-14 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_shop', '0015_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurTeams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=20)),
                ('member_position', models.CharField(max_length=20)),
                ('member_pic', models.ImageField(upload_to='site_images')),
            ],
        ),
    ]
