# Generated by Django 4.0 on 2021-12-14 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_shop', '0016_ourteams'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OurTeams',
            new_name='OurTeam',
        ),
    ]
