# Generated by Django 4.0 on 2021-12-14 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('new_shop', '0020_delete_blockpostdetails_delete_blogpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=20)),
                ('published_date', models.DateField(auto_now=True)),
                ('blog_title', models.CharField(max_length=100)),
                ('blog_image', models.ImageField(upload_to='site_images')),
            ],
        ),
        migrations.CreateModel(
            name='BlockPostDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_desc', models.TextField()),
                ('blog_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_shop.blogpost')),
            ],
        ),
    ]
