# Generated by Django 4.0 on 2021-12-16 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_shop', '0035_delete_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='sizes_available',
            field=models.CharField(choices=[('X', 'X'), ('M', 'M'), ('L', 'L'), ('Extra_Large', 'XL'), ('XX_large', 'XLL')], max_length=50, verbose_name='Size Avaailable'),
        ),
    ]
