# Generated by Django 4.0 on 2021-12-31 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_shop', '0050_item_secondary_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item_Secondary_Image',
            new_name='ItemSecondaryImage',
        ),
    ]
