# Generated by Django 4.0 on 2022-01-02 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('new_shop', '0051_rename_item_secondary_image_itemsecondaryimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardproduct',
            name='cartegory',
        ),
        migrations.AddField(
            model_name='cardproduct',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='new_shop.category'),
            preserve_default=False,
        ),
    ]
