# Generated by Django 4.0 on 2022-01-08 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_shop', '0054_rename_original_price_item_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='img',
            new_name='image',
        ),
    ]
