# Generated by Django 4.0 on 2022-01-08 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_shop', '0056_alter_item_discount_price_alter_item_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.FloatField(default=300, verbose_name='Price'),
            preserve_default=False,
        ),
    ]
