# Generated by Django 4.0 on 2022-02-02 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_shop', '0061_rename_start_date_order_date_remove_order_items_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='author',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='blog_image',
            field=models.ImageField(upload_to='site_images/blog_img'),
        ),
        migrations.AlterField(
            model_name='cardproduct',
            name='img',
            field=models.ImageField(upload_to='site_images/card_img'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='profile_pic',
            field=models.ImageField(upload_to='site_images/feedback_img'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='username',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='frontpagecarousel',
            name='background_image',
            field=models.ImageField(upload_to='site_images/carousel_img'),
        ),
        migrations.AlterField(
            model_name='frontpagecarousel',
            name='offer_product',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='frontpagecarousel',
            name='offer_title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(upload_to='site_images/item_img', verbose_name='Item Image'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Item Name'),
        ),
        migrations.AlterField(
            model_name='itemsecondaryimage',
            name='image',
            field=models.ImageField(upload_to='site_images/other_item_img', verbose_name='Secondary Image'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='img',
            field=models.ImageField(upload_to='site_images/offer_img'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='product_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ourteam',
            name='member_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ourteam',
            name='member_pic',
            field=models.ImageField(upload_to='site_images/team_img'),
        ),
        migrations.AlterField(
            model_name='ourteam',
            name='member_position',
            field=models.CharField(max_length=100),
        ),
    ]
