# Generated by Django 4.0 on 2022-02-18 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_shop', '0067_rename_username_order_first_name_order_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_note',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
