# Generated by Django 4.0 on 2022-05-31 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_shop', '0076_alter_item_image_alter_item_item_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Created', 'Created'), ('Processing', 'Processing'), ('Cancelled', 'Cancelled'), ('Shipped', 'Shipped'), ('Completed', 'Completed')], default='Pending', max_length=200),
        ),
    ]
